;**
;**	Room Defines
;**
;**	Leisure Suit Larry goes "Looking for Love" (in Several Wrong Places)
;**		by Al Lowe
;**
;**	Last Update:	October 13, 1988
;**


  0 -- "'cause Al used to be a room zero-kind of guy!"
  1 -- Menu (outputs to script.997; not 001 as supposed)
  2 -- Inventory wrangler
  3 -- DOORS
  4 -- BASS_SETTER
  5 -- debug logics
  6 -- AIRPLANES
  7 -- barber setup
  8 -- 
  9 -- Boss Key
 10 -- copy check room
 11 -- outside the tv studio:  KROD (get it?)
101 -- TV studio reception area
102 -- Green Room
103 -- Dating Connection studio
104 -- Lucky Life Lottery studio
 12 -- Hollywood
 13 -- non-Dark Alley
 14 -- quickie mart
114 -- Quickie mart interior
 15 -- Ethnomusicology Shoppe Exterior
115 -- Ethnomusicology Shoppe Interior
 16 -- outside of Rodeo Drive clothing store
116 -- clothing store interior
 17 -- Brown Derby
 18 -- drug store exterior
118 -- drug store
 19 -- Disneyland
 20 -- LA Bonaventure Hotel
 21 -- downtown LA 
 22 -- Queen Larry, the Loose Goose, Scurvy Dog Saloon
 23 -- Eve's House
 24 -- Unreversal Studios
 25 -- Hairy Reams, the LA barber 
125 -- inside LA barber shop
 26 -- the Dock
 27 -- gangplank
 28 -- cruise ship departure
 31 -- ship map
131 -- ship map, Larry escapes & sails away in lifeboat
 32 -- Larry's cabin
 33 -- Mother's cabin
 34 -- ship's pool
134 -- underwater at the Ship's swimming pool
 35 -- ship's bar
 36 -- ship's bridge
 37 -- ship's barber
 38 -- ship's lifeboat
138 -- Victory(?) At Sea
 40 -- resort landscape maze
 41 -- Nude Beach
 42 -- On The Beach
 43 -- Gay Beach
 44 -- Larry's room at the resort
 45 -- Resort barber shop
 47 -- Resort Restaurant
 48 -- Cliff maze spoof
 50 -- Aeroporto exterior
 51 -- Airport Barber Shop exterior
151 -- Airport Barber Shop
 52 -- Aeroporto Ticket Counter
152 -- BOOM!!
 53 -- Customs
 54 -- American Terroristor Luggage
 55 -- Snack Bar
 56 -- riding the airport moving sidewalk
 57 -- Airport waiting room
 58 -- the jetway from the Airport to the Airplane
 61 -- airplane first class
 62 -- Larry's airplane seat
 63 -- airplane rear
 64 -- fresh out of the airplane
 65 -- parachuting to the island
 70 -- hanging in the Parachute Tree
 71 -- Killer Bees
 72 -- Monte, the jungle python
 73 -- Jungle Quicksand
 74 -- Piranha River
 75 -- Kalalau Beach
 76 -- Chief's hut
 77 -- native village central
 78 -- Witch Doctor's hut
178 -- Witch doctor's barber scene
 79 -- Chasm of Doom
 80 -- Before the Glacier
 81 -- Glacier Pointless
181 -- above Glacier
 82 -- Top of Volcano Fortress
 83 -- Dr. Nonookee's elevator shaft
 84 -- Dr. Nonookee's chambers
 85 -- the SI copter rescue
 86 -- consummation
 90 -- Banner Screen and Credits
 91 -- Eve dumps Larry
 92 -- Nontonyte long shot
 93 -- Dr. Nonookee's throne room
 95 -- Henchette seduction
 96 -- KGB torture
 99 -- speed test room
200 -- LA region
300 -- airport region
301 -- henchette dynamic
400 -- resort region
401 -- resort beach region
500 -- airport region
600 -- airplane region 
700 -- island region

